Repository betalgo/openai, pull requests merged in 2023-07, with the labels that each got.

#334 Some refactoring about functions
  OpenAI.Playground/Program.cs
  OpenAI.Playground/TestHelpers/ChatCompletionTestHelper.cs
  OpenAI.SDK/Builders/FunctionDefinitionBuilder.cs
  OpenAI.SDK/ObjectModels/RequestModels/ChatCompletionCreateRequest.cs
  OpenAI.SDK/ObjectModels/RequestModels/ChatMessage.cs
  OpenAI.SDK/ObjectModels/SharedModels/FunctionParameters.cs
Labels: Code Review Needed

#320 Several improvements / fixes for functions
  OpenAI.Playground/TestHelpers/ChatCompletionTestHelper.cs
  OpenAI.SDK/Builders/FunctionDefinitionBuilder.cs
  OpenAI.SDK/Managers/OpenAIFile.cs
  OpenAI.SDK/ObjectModels/RequestModels/ChatMessage.cs
  OpenAI.SDK/ObjectModels/RequestModels/FunctionCall.cs
  OpenAI.SDK/ObjectModels/RequestModels/FunctionDefinition.cs
  OpenAI.SDK/ObjectModels/ResponseModels/BaseResponse.cs
  OpenAI.SDK/ObjectModels/SharedModels/FunctionParameters.cs
Labels: question

#313 Enable to set FunctionCall to AssistantRole's ChatMessage
  OpenAI.SDK/ObjectModels/RequestModels/ChatMessage.cs
Labels: enhancement

#337 Version 7.1.3
  OpenAI.Playground/Program.cs
  OpenAI.Playground/TestHelpers/ChatCompletionTestHelper.cs
  OpenAI.SDK/Builders/FunctionDefinitionBuilder.cs
  OpenAI.SDK/Managers/OpenAIFile.cs
  OpenAI.SDK/ObjectModels/RequestModels/ChatCompletionCreateRequest.cs
  OpenAI.SDK/ObjectModels/RequestModels/ChatMessage.cs
  OpenAI.SDK/ObjectModels/RequestModels/FunctionCall.cs
  OpenAI.SDK/ObjectModels/RequestModels/FunctionDefinition.cs
  OpenAI.SDK/ObjectModels/ResponseModels/BaseResponse.cs
  OpenAI.SDK/ObjectModels/SharedModels/FunctionParameters.cs
Labels: Code Review Needed
